conky.config = {
    alignment = 'top_left',
    xinerama_head = 0,
    gap_x = 44,
    gap_y = 64,
    minimum_width = 300,
    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    double_buffer = true,
    update_interval = 1.0,
    use_xft = true,
    font = 'JetBrainsMono Nerd Font:size=10',
    override_utf8_locale = true,
    draw_shades = false,
    default_color = 'C98A52',
    color1 = 'FFB454',
    color2 = 'E8743B',
    color3 = '8FB36B',
}
conky.text = [[
${color1}┌─ AMBER OS ─────────────────${color}
${color1}❯${color} ${nodename}
${color2}uptime${color}  ${uptime_short}
${color2}load  ${color}  ${loadavg 1} ${color3}/ ${execi 86400 nproc} cpu${color}
${color2}cpu   ${color}  ${if_match ${cpu}<100} ${endif}${if_match ${cpu}<10} ${endif}${cpu}%  ${color1}${cpubar 6,120}${color}
${color2}ram   ${color}  ${if_match ${memperc}<100} ${endif}${if_match ${memperc}<10} ${endif}${memperc}%  ${color1}${membar 6,120}${color}
${color2}disk  ${color}  ${if_match ${fs_used_perc /}<100} ${endif}${if_match ${fs_used_perc /}<10} ${endif}${fs_used_perc /}%  ${color1}${fs_bar 6,120 /}${color}
${color2}bat   ${color}  ${if_match ${battery_percent BAT0}<100} ${endif}${if_match ${battery_percent BAT0}<10} ${endif}${battery_percent BAT0}%  ${if_match ${battery_percent BAT0}<30}${color D9544E}${else}${if_match ${battery_percent BAT0}<60}${color1}${else}${color3}${endif}${endif}${battery_bar 6,120 BAT0}${color}
${color2}net   ${color}  ${color3}↓${color}${downspeed wlo1} ${color3}↑${color}${upspeed wlo1}
${color1}└────────────────────────────${color}
]]
